from django.shortcuts import render
from django.http import HttpResponse
from django.views import View

    # Create your views here.
def home(request):
  context = {
      'page_title': 'Home Page',
      'page_heading': 'Welcome to the Home Page',
      'page_content': 'Hello Django!!',
  }
  return render(request, 'bootswatch.html', context)

def about(request):
  context = {
      'page_title': 'About Page',
      'page_heading': 'Welcome to the About Page',
      'page_content': 'About Page!',
  }
  return render(request, 'bootswatch.html', context)

def function_view(request):
        context = {
            'page_title': 'Function-Based View',
            'page_heading': 'Welcome to the Function-Based View',
            'page_content': 'This is the content generated by the function-based view.',
        }
        return render(request, 'bootswatch.html', context)

def contact(request):
  context = {
      'page_title': 'Contact Page',
      'page_heading': 'Welcome to the Contact Page',
      'page_content': 'Contact information.',
  }
  return render(request, 'bootswatch.html', context)

class ClassView(View):
        def get(self, request):
            context = {
                'page_title': 'Class-Based View',
                'page_heading': 'Welcome to the Class-Based View',
                'page_content': 'This is the content generated by the class-based view.',
            }
            return render(request, 'bootswatch.html', context)

class gallery(View):
  def get(self, request):
      context = {
          'page_title': 'Gallery',
          'page_heading': 'Welcome to the Gallery',
          'page_content': 'This is the Gallery.',
      }
      return render(request, 'bootswatch.html', context)